blog/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :articles
  root 'home#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end	
	
	def show
		@article = Article.find(params[:id])
	end

	def new
	end

	def create
		@article = Article.new(article_params)

		@article.save
		redirect_to @article
	end

	private
	def article_params
		params.require(:article).permit(:title,:text)
	end



end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New Article', new_article_path %>

<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
	</tr>
	
	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.text %></td>
		</tr>
	<% end %>
</table>				

blog/app/views/articles/new.html.erb
<h1> New Article </h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Test:</strong>
	<%= @article.text %>
</p>		

<% link_to 'Back', articles_path %>

blog/app/views/home/index.html.erb
<h1>Hello!</h1>
<%= link_to 'My Blog', controller: 'articles' %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>